name: "release-flag-action"
author: "DeeepDev"
description: This action is used to create powerful banners for your packages.
inputs:
  repo_github_object:
    description: "repository github object"
    required: true
  version:
    description: "released version"
    required: true
  prerelease:
    description: "whether it is prerelease or not"
    required: false
    default: "false"
  flag-quality:
    description: "DPI of the flag image produced"
    required: false
    default: "150"
  telegram_to:
    description: "chat_id to send the message to"
    required: true
  telegram_token:
    description: "telegram bot token"
    required: true
  telegram_message:
    description: "telegram message"
    required: true
  telegram_message_format:
    description: "telegram message format: MarkdownV2 or HTML or Markdown"
    required: false
    default: "Markdown"
outputs:
  output_flag_buf:
    description: "release flag photo buffer"
  output_flag_path:
    description: "release flag photo output path"
runs:
  using: "node16"
  main: "dist/index.cjs"
