# Run unit tests and the action itself
name: tests

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Inter Google Font
        run: |
          wget -O Inter.zip https://fonts.google.com/download?family=Inter
          unzip -d inter/ Inter.zip
          mv inter /usr/share/fonts/
          fc-cache -fv
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - run: pnpm install
      - run: pnpm build
      - id: create_release_flag
        uses: ./
        with:
          repo_github_object: ${{ toJson(github) }}
          version: 2.0.0
          prerelease: "true"
      - name: send-message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "heyyyyyy"
          photo: "${{ steps.create_release_flag.outputs.photo_path }}"
