# Validate the code and the action itself
name: validate

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm format:check
      - run: pnpm type-check
      - run: pnpm build
      - id: create_release_flag
        uses: ./
        with:
          repo_github_object: ${{ toJson(github) }}
          version: 2.3.4
          prerelease: "false"
      # - name: send-message
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: ${{ secrets.TELEGRAM_TO }}
      #     token: ${{ secrets.TELEGRAM_TOKEN }}
      #     message: "message"
      #     photo: "${{ steps.create_release_flag.outputs.output_flag_path }}"
